name: NestersAndNomads
favicon: null
layout_spectrum: 0.24257
typography_spectrum: 0.9507253852207214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5da6a5'
    - '#b4b4b4'
    - '#3375a9'
    - '#434749'
  brandStrength: 0.5
  lightness: 0.9048189409077168
  saturation: 0.8792723335791379
  rhythmicContrast: 0.5
purpose: []
